# Generated by Django 5.1.1 on 2024-09-24 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libros',
            old_name='rating',
            new_name='calificacion',
        ),
    ]
