# Generated by Django 5.1.1 on 2024-09-25 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_rename_rating_libros_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='calificacion',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
