# Generated by Django 5.1.1 on 2024-09-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alter_libros_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
