# Generated by Django 5.1.1 on 2024-09-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_libros_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='bestseller',
            field=models.BooleanField(default=False),
        ),
    ]
