# Generated by Django 5.1.1 on 2024-09-26 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_rename_libros_libro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'Autores'},
        ),
    ]
