# Generated by Django 5.1.1 on 2024-10-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_alter_libro_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='apellido',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
