# Generated by Django 5.1.1 on 2024-10-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0014_pais_alter_direccion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='disponible_en',
            field=models.ManyToManyField(to='biblioteca.pais'),
        ),
    ]
