# Generated by Django 5.1.1 on 2024-10-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(max_length=255, verbose_name='Reseña'),
        ),
        migrations.AlterField(
            model_name='review',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Nombre de Usuario'),
        ),
    ]
